# Generated by Django 5.2.6 on 2025-11-05 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="commented_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
